import turtle

def turtle_print(try_number):
    t = turtle.Turtle()
    t.shape('turtle')
    t.color("black")
    if try_number == 9:
        t.forward(100)
        t.left(180)
        t.forward(50)
        t.right(90)
        t.forward(20)
        t.color("white")
    if try_number == 8:
        t.forward(100)
        t.left(180)
        t.forward(50)
        t.right(90)
        t.forward(40)
        t.color("white")
    if try_number == 7:
        t.forward(100)
        t.left(180)
        t.forward(50)
        t.right(90)
        t.forward(60)
        t.color("white")
    if try_number == 6:
        t.forward(100)
        t.left(180)
        t.forward(50)
        t.right(90)
        t.forward(140)
        t.color("white")
    if try_number == 5:
        t.forward(100)
        t.left(180)
        t.forward(50)
        t.right(90)
        t.forward(140)
        t.right(90)
        t.forward(50)
        t.color("white")
    if try_number == 4:
        t.forward(100)
        t.left(180)
        t.forward(50)
        t.right(90)
        t.forward(140)
        t.right(90)
        t.forward(50)
        t.right(90)
        t.forward(20)
        t.color("white")
    if try_number == 3:
        t.forward(100)
        t.left(180)
        t.forward(50)
        t.right(90)
        t.forward(140)
        t.right(90)
        t.forward(50)
        t.right(90)
        t.forward(20)
        t.dot(20, "black")
        t.forward(20)
        t.color("white")

    if try_number == 2:
        t.forward(100)
        t.left(180)
        t.forward(50)
        t.right(90)
        t.forward(140)
        t.right(90)
        t.forward(50)
        t.right(90)
        t.forward(20)
        t.dot(20, "black")
        t.forward(20)
        t.right(90)
        t.forward(15)
        t.left(180)
        t.forward(30)
        t.right(180)
        t.forward(15)
        t.left(90)
        t.color("white")

    if try_number == 1:
        t.forward(100)
        t.left(180)
        t.forward(50)
        t.right(90)
        t.forward(140)
        t.right(90)
        t.forward(50)
        t.right(90)
        t.forward(20)
        t.dot(20, "black")
        t.forward(20)
        t.right(90)
        t.forward(15)
        t.left(180)
        t.forward(30)
        t.right(180)
        t.forward(15)
        t.left(90)
        t.forward(30)
        t.color("white")

    if try_number == 0:
        t.color("red")
        t.forward(100)
        t.left(180)
        t.forward(50)
        t.right(90)
        t.forward(140)
        t.right(90)
        t.forward(50)
        t.right(90)
        t.forward(20)
        t.dot(20, "Red")
        t.forward(20)
        t.right(90)
        t.forward(15)
        t.left(180)
        t.forward(30)
        t.right(180)
        t.forward(15)
        t.left(90)
        t.forward(30)
        t.left(45)
        t.forward(20)
        t.left(180)
        t.forward(20)
        t.right(250)
        t.forward(20)
        t.color("white")
        t.goto(200,100)
        t.color("red")
        t.write("You lost :(", align='right')
        t.color("white")
        turtle.done()




if __name__ == "__main__":
    turtle_print(0)